### ISSUE TITLE
No texture

### ISSUE THREAD

**Issue by usser1976** [ByAlperenS/ThorHammer#7]
Somehow I don't see a texture for the hammer.
The item is in the inventory and also works, it is just not visible.

**Comment by ByAlperenS** [comment]
What is your server version?

**Comment by usser1976** [comment]
The last Altay Build
Minecraft: Bedrock Edition v1.16.200 (protocol version 422)

**Comment by ByAlperenS** [comment]
You try, please

**Comment by usser1976** [comment]
🤔 no 
![20210222_222619](https://user-images.githubusercontent.com/46025756/108772280-15052880-755d-11eb-9be5-efefdfac1d91.jpg)

**Comment by ByAlperenS** [comment]
Did you uploded resource pack ?
